/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateOpsIndex.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
const A1Z26CipherDecode = require("./A1Z26CipherDecode.js")
const A1Z26CipherEncode = require("./A1Z26CipherEncode.js")
const ADD = require("./ADD.js")
const AESDecrypt = require("./AESDecrypt.js")
const AESEncrypt = require("./AESEncrypt.js")
const AESKeyUnwrap = require("./AESKeyUnwrap.js")
const AESKeyWrap = require("./AESKeyWrap.js")
const AMFDecode = require("./AMFDecode.js")
const AMFEncode = require("./AMFEncode.js")
const AND = require("./AND.js")
const AddLineNumbers = require("./AddLineNumbers.js")
const AddTextToImage = require("./AddTextToImage.js")
const Adler32Checksum = require("./Adler32Checksum.js")
const AffineCipherDecode = require("./AffineCipherDecode.js")
const AffineCipherEncode = require("./AffineCipherEncode.js")
const AnalyseHash = require("./AnalyseHash.js")
const Argon2 = require("./Argon2.js")
const Argon2Compare = require("./Argon2Compare.js")
const AtbashCipher = require("./AtbashCipher.js")
const AvroToJSON = require("./AvroToJSON.js")
const BLAKE2b = require("./BLAKE2b.js")
const BLAKE2s = require("./BLAKE2s.js")
const BSONDeserialise = require("./BSONDeserialise.js")
const BSONSerialise = require("./BSONSerialise.js")
const BaconCipherDecode = require("./BaconCipherDecode.js")
const BaconCipherEncode = require("./BaconCipherEncode.js")
const Bcrypt = require("./Bcrypt.js")
const BcryptCompare = require("./BcryptCompare.js")
const BcryptParse = require("./BcryptParse.js")
const BifidCipherDecode = require("./BifidCipherDecode.js")
const BifidCipherEncode = require("./BifidCipherEncode.js")
const BitShiftLeft = require("./BitShiftLeft.js")
const BitShiftRight = require("./BitShiftRight.js")
const BlowfishDecrypt = require("./BlowfishDecrypt.js")
const BlowfishEncrypt = require("./BlowfishEncrypt.js")
const BlurImage = require("./BlurImage.js")
const Bombe = require("./Bombe.js")
const Bzip2Compress = require("./Bzip2Compress.js")
const Bzip2Decompress = require("./Bzip2Decompress.js")
const CBORDecode = require("./CBORDecode.js")
const CBOREncode = require("./CBOREncode.js")
const CMAC = require("./CMAC.js")
const CRC16Checksum = require("./CRC16Checksum.js")
const CRC32Checksum = require("./CRC32Checksum.js")
const CRC8Checksum = require("./CRC8Checksum.js")
const CSSBeautify = require("./CSSBeautify.js")
const CSSMinify = require("./CSSMinify.js")
const CSSSelector = require("./CSSSelector.js")
const CSVToJSON = require("./CSVToJSON.js")
const CTPH = require("./CTPH.js")
const CaesarBoxCipher = require("./CaesarBoxCipher.js")
const CartesianProduct = require("./CartesianProduct.js")
const CetaceanCipherDecode = require("./CetaceanCipherDecode.js")
const CetaceanCipherEncode = require("./CetaceanCipherEncode.js")
const ChaCha = require("./ChaCha.js")
const ChangeIPFormat = require("./ChangeIPFormat.js")
const ChiSquare = require("./ChiSquare.js")
const CipherSaber2Decrypt = require("./CipherSaber2Decrypt.js")
const CipherSaber2Encrypt = require("./CipherSaber2Encrypt.js")
const CitrixCTX1Decode = require("./CitrixCTX1Decode.js")
const CitrixCTX1Encode = require("./CitrixCTX1Encode.js")
const Colossus = require("./Colossus.js")
const Comment = require("./Comment.js")
const CompareCTPHHashes = require("./CompareCTPHHashes.js")
const CompareSSDEEPHashes = require("./CompareSSDEEPHashes.js")
const ConditionalJump = require("./ConditionalJump.js")
const ContainImage = require("./ContainImage.js")
const ConvertArea = require("./ConvertArea.js")
const ConvertCoordinateFormat = require("./ConvertCoordinateFormat.js")
const ConvertDataUnits = require("./ConvertDataUnits.js")
const ConvertDistance = require("./ConvertDistance.js")
const ConvertImageFormat = require("./ConvertImageFormat.js")
const ConvertMass = require("./ConvertMass.js")
const ConvertSpeed = require("./ConvertSpeed.js")
const ConvertToNATOAlphabet = require("./ConvertToNATOAlphabet.js")
const CountOccurrences = require("./CountOccurrences.js")
const CoverImage = require("./CoverImage.js")
const CropImage = require("./CropImage.js")
const DESDecrypt = require("./DESDecrypt.js")
const DESEncrypt = require("./DESEncrypt.js")
const DNSOverHTTPS = require("./DNSOverHTTPS.js")
const DechunkHTTPResponse = require("./DechunkHTTPResponse.js")
const DecodeNetBIOSName = require("./DecodeNetBIOSName.js")
const DecodeText = require("./DecodeText.js")
const DefangIPAddresses = require("./DefangIPAddresses.js")
const DefangURL = require("./DefangURL.js")
const DeriveEVPKey = require("./DeriveEVPKey.js")
const DeriveHKDFKey = require("./DeriveHKDFKey.js")
const DerivePBKDF2Key = require("./DerivePBKDF2Key.js")
const DetectFileType = require("./DetectFileType.js")
const Diff = require("./Diff.js")
const DisassembleX86 = require("./DisassembleX86.js")
const DitherImage = require("./DitherImage.js")
const Divide = require("./Divide.js")
const DropBytes = require("./DropBytes.js")
const ELFInfo = require("./ELFInfo.js")
const EncodeNetBIOSName = require("./EncodeNetBIOSName.js")
const EncodeText = require("./EncodeText.js")
const Enigma = require("./Enigma.js")
const Entropy = require("./Entropy.js")
const EscapeString = require("./EscapeString.js")
const EscapeUnicodeCharacters = require("./EscapeUnicodeCharacters.js")
const ExpandAlphabetRange = require("./ExpandAlphabetRange.js")
const ExtractDates = require("./ExtractDates.js")
const ExtractDomains = require("./ExtractDomains.js")
const ExtractEXIF = require("./ExtractEXIF.js")
const ExtractEmailAddresses = require("./ExtractEmailAddresses.js")
const ExtractFilePaths = require("./ExtractFilePaths.js")
const ExtractFiles = require("./ExtractFiles.js")
const ExtractID3 = require("./ExtractID3.js")
const ExtractIPAddresses = require("./ExtractIPAddresses.js")
const ExtractLSB = require("./ExtractLSB.js")
const ExtractMACAddresses = require("./ExtractMACAddresses.js")
const ExtractRGBA = require("./ExtractRGBA.js")
const ExtractURLs = require("./ExtractURLs.js")
const Filter = require("./Filter.js")
const FindReplace = require("./FindReplace.js")
const Fletcher16Checksum = require("./Fletcher16Checksum.js")
const Fletcher32Checksum = require("./Fletcher32Checksum.js")
const Fletcher64Checksum = require("./Fletcher64Checksum.js")
const Fletcher8Checksum = require("./Fletcher8Checksum.js")
const FlipImage = require("./FlipImage.js")
const Fork = require("./Fork.js")
const FormatMACAddresses = require("./FormatMACAddresses.js")
const FrequencyDistribution = require("./FrequencyDistribution.js")
const FromBCD = require("./FromBCD.js")
const FromBase = require("./FromBase.js")
const FromBase32 = require("./FromBase32.js")
const FromBase45 = require("./FromBase45.js")
const FromBase58 = require("./FromBase58.js")
const FromBase62 = require("./FromBase62.js")
const FromBase64 = require("./FromBase64.js")
const FromBase85 = require("./FromBase85.js")
const FromBinary = require("./FromBinary.js")
const FromBraille = require("./FromBraille.js")
const FromCaseInsensitiveRegex = require("./FromCaseInsensitiveRegex.js")
const FromCharcode = require("./FromCharcode.js")
const FromDecimal = require("./FromDecimal.js")
const FromHTMLEntity = require("./FromHTMLEntity.js")
const FromHex = require("./FromHex.js")
const FromHexContent = require("./FromHexContent.js")
const FromHexdump = require("./FromHexdump.js")
const FromMessagePack = require("./FromMessagePack.js")
const FromMorseCode = require("./FromMorseCode.js")
const FromOctal = require("./FromOctal.js")
const FromPunycode = require("./FromPunycode.js")
const FromQuotedPrintable = require("./FromQuotedPrintable.js")
const FromUNIXTimestamp = require("./FromUNIXTimestamp.js")
const FuzzyMatch = require("./FuzzyMatch.js")
const GOSTHash = require("./GOSTHash.js")
const GenerateAllHashes = require("./GenerateAllHashes.js")
const GenerateDeBruijnSequence = require("./GenerateDeBruijnSequence.js")
const GenerateHOTP = require("./GenerateHOTP.js")
const GenerateImage = require("./GenerateImage.js")
const GenerateLoremIpsum = require("./GenerateLoremIpsum.js")
const GeneratePGPKeyPair = require("./GeneratePGPKeyPair.js")
const GenerateQRCode = require("./GenerateQRCode.js")
const GenerateRSAKeyPair = require("./GenerateRSAKeyPair.js")
const GenerateTOTP = require("./GenerateTOTP.js")
const GenerateUUID = require("./GenerateUUID.js")
const GenericCodeBeautify = require("./GenericCodeBeautify.js")
const GetAllCasings = require("./GetAllCasings.js")
const GetTime = require("./GetTime.js")
const GroupIPAddresses = require("./GroupIPAddresses.js")
const Gunzip = require("./Gunzip.js")
const Gzip = require("./Gzip.js")
const HAS160 = require("./HAS160.js")
const HASSHClientFingerprint = require("./HASSHClientFingerprint.js")
const HASSHServerFingerprint = require("./HASSHServerFingerprint.js")
const HMAC = require("./HMAC.js")
const HTMLToText = require("./HTMLToText.js")
const HTTPRequest = require("./HTTPRequest.js")
const HammingDistance = require("./HammingDistance.js")
const HaversineDistance = require("./HaversineDistance.js")
const Head = require("./Head.js")
const HeatmapChart = require("./HeatmapChart.js")
const HexDensityChart = require("./HexDensityChart.js")
const HexToObjectIdentifier = require("./HexToObjectIdentifier.js")
const HexToPEM = require("./HexToPEM.js")
const ImageBrightnessContrast = require("./ImageBrightnessContrast.js")
const ImageFilter = require("./ImageFilter.js")
const ImageHueSaturationLightness = require("./ImageHueSaturationLightness.js")
const ImageOpacity = require("./ImageOpacity.js")
const IndexOfCoincidence = require("./IndexOfCoincidence.js")
const InvertImage = require("./InvertImage.js")
const JA3Fingerprint = require("./JA3Fingerprint.js")
const JA3SFingerprint = require("./JA3SFingerprint.js")
const JPathExpression = require("./JPathExpression.js")
const JSONBeautify = require("./JSONBeautify.js")
const JSONMinify = require("./JSONMinify.js")
const JSONToCSV = require("./JSONToCSV.js")
const JWTDecode = require("./JWTDecode.js")
const JWTSign = require("./JWTSign.js")
const JWTVerify = require("./JWTVerify.js")
const JavaScriptBeautify = require("./JavaScriptBeautify.js")
const JavaScriptMinify = require("./JavaScriptMinify.js")
const JavaScriptParser = require("./JavaScriptParser.js")
const Jump = require("./Jump.js")
const Keccak = require("./Keccak.js")
const LMHash = require("./LMHash.js")
const LS47Decrypt = require("./LS47Decrypt.js")
const LS47Encrypt = require("./LS47Encrypt.js")
const LZ4Compress = require("./LZ4Compress.js")
const LZ4Decompress = require("./LZ4Decompress.js")
const LZMACompress = require("./LZMACompress.js")
const LZMADecompress = require("./LZMADecompress.js")
const LZStringCompress = require("./LZStringCompress.js")
const LZStringDecompress = require("./LZStringDecompress.js")
const Label = require("./Label.js")
const LevenshteinDistance = require("./LevenshteinDistance.js")
const Lorenz = require("./Lorenz.js")
const LuhnChecksum = require("./LuhnChecksum.js")
const MD2 = require("./MD2.js")
const MD4 = require("./MD4.js")
const MD5 = require("./MD5.js")
const MD6 = require("./MD6.js")
const Magic = require("./Magic.js")
const Mean = require("./Mean.js")
const Median = require("./Median.js")
const Merge = require("./Merge.js")
const MicrosoftScriptDecoder = require("./MicrosoftScriptDecoder.js")
const MultipleBombe = require("./MultipleBombe.js")
const Multiply = require("./Multiply.js")
const NOT = require("./NOT.js")
const NTHash = require("./NTHash.js")
const NormaliseImage = require("./NormaliseImage.js")
const NormaliseUnicode = require("./NormaliseUnicode.js")
const Numberwang = require("./Numberwang.js")
const OR = require("./OR.js")
const ObjectIdentifierToHex = require("./ObjectIdentifierToHex.js")
const OffsetChecker = require("./OffsetChecker.js")
const OpticalCharacterRecognition = require("./OpticalCharacterRecognition.js")
const PEMToHex = require("./PEMToHex.js")
const PGPDecrypt = require("./PGPDecrypt.js")
const PGPDecryptAndVerify = require("./PGPDecryptAndVerify.js")
const PGPEncrypt = require("./PGPEncrypt.js")
const PGPEncryptAndSign = require("./PGPEncryptAndSign.js")
const PGPVerify = require("./PGPVerify.js")
const PHPDeserialize = require("./PHPDeserialize.js")
const PLISTViewer = require("./PLISTViewer.js")
const PadLines = require("./PadLines.js")
const ParseASN1HexString = require("./ParseASN1HexString.js")
const ParseColourCode = require("./ParseColourCode.js")
const ParseDateTime = require("./ParseDateTime.js")
const ParseIPRange = require("./ParseIPRange.js")
const ParseIPv4Header = require("./ParseIPv4Header.js")
const ParseIPv6Address = require("./ParseIPv6Address.js")
const ParseObjectIDTimestamp = require("./ParseObjectIDTimestamp.js")
const ParseQRCode = require("./ParseQRCode.js")
const ParseSSHHostKey = require("./ParseSSHHostKey.js")
const ParseTCP = require("./ParseTCP.js")
const ParseTLV = require("./ParseTLV.js")
const ParseUDP = require("./ParseUDP.js")
const ParseUNIXFilePermissions = require("./ParseUNIXFilePermissions.js")
const ParseURI = require("./ParseURI.js")
const ParseUserAgent = require("./ParseUserAgent.js")
const ParseX509Certificate = require("./ParseX509Certificate.js")
const PlayMedia = require("./PlayMedia.js")
const PowerSet = require("./PowerSet.js")
const ProtobufDecode = require("./ProtobufDecode.js")
const ProtobufEncode = require("./ProtobufEncode.js")
const PseudoRandomNumberGenerator = require("./PseudoRandomNumberGenerator.js")
const RC2Decrypt = require("./RC2Decrypt.js")
const RC2Encrypt = require("./RC2Encrypt.js")
const RC4 = require("./RC4.js")
const RC4Drop = require("./RC4Drop.js")
const RIPEMD = require("./RIPEMD.js")
const ROT13 = require("./ROT13.js")
const ROT13BruteForce = require("./ROT13BruteForce.js")
const ROT47 = require("./ROT47.js")
const ROT47BruteForce = require("./ROT47BruteForce.js")
const ROT8000 = require("./ROT8000.js")
const RSADecrypt = require("./RSADecrypt.js")
const RSAEncrypt = require("./RSAEncrypt.js")
const RSASign = require("./RSASign.js")
const RSAVerify = require("./RSAVerify.js")
const Rabbit = require("./Rabbit.js")
const RailFenceCipherDecode = require("./RailFenceCipherDecode.js")
const RailFenceCipherEncode = require("./RailFenceCipherEncode.js")
const RandomizeColourPalette = require("./RandomizeColourPalette.js")
const RawDeflate = require("./RawDeflate.js")
const RawInflate = require("./RawInflate.js")
const Register = require("./Register.js")
const RegularExpression = require("./RegularExpression.js")
const RemoveDiacritics = require("./RemoveDiacritics.js")
const RemoveEXIF = require("./RemoveEXIF.js")
const RemoveLineNumbers = require("./RemoveLineNumbers.js")
const RemoveNullBytes = require("./RemoveNullBytes.js")
const RemoveWhitespace = require("./RemoveWhitespace.js")
const RenderImage = require("./RenderImage.js")
const RenderMarkdown = require("./RenderMarkdown.js")
const ResizeImage = require("./ResizeImage.js")
const Return = require("./Return.js")
const Reverse = require("./Reverse.js")
const RotateImage = require("./RotateImage.js")
const RotateLeft = require("./RotateLeft.js")
const RotateRight = require("./RotateRight.js")
const SHA0 = require("./SHA0.js")
const SHA1 = require("./SHA1.js")
const SHA2 = require("./SHA2.js")
const SHA3 = require("./SHA3.js")
const SIGABA = require("./SIGABA.js")
const SM3 = require("./SM3.js")
const SM4Decrypt = require("./SM4Decrypt.js")
const SM4Encrypt = require("./SM4Encrypt.js")
const SQLBeautify = require("./SQLBeautify.js")
const SQLMinify = require("./SQLMinify.js")
const SSDEEP = require("./SSDEEP.js")
const SUB = require("./SUB.js")
const ScanForEmbeddedFiles = require("./ScanForEmbeddedFiles.js")
const ScatterChart = require("./ScatterChart.js")
const Scrypt = require("./Scrypt.js")
const SeriesChart = require("./SeriesChart.js")
const SetDifference = require("./SetDifference.js")
const SetIntersection = require("./SetIntersection.js")
const SetUnion = require("./SetUnion.js")
const Shake = require("./Shake.js")
const SharpenImage = require("./SharpenImage.js")
const ShowBase64Offsets = require("./ShowBase64Offsets.js")
const ShowOnMap = require("./ShowOnMap.js")
const Shuffle = require("./Shuffle.js")
const Sleep = require("./Sleep.js")
const Snefru = require("./Snefru.js")
const Sort = require("./Sort.js")
const Split = require("./Split.js")
const SplitColourChannels = require("./SplitColourChannels.js")
const StandardDeviation = require("./StandardDeviation.js")
const Streebog = require("./Streebog.js")
const Strings = require("./Strings.js")
const StripHTMLTags = require("./StripHTMLTags.js")
const StripHTTPHeaders = require("./StripHTTPHeaders.js")
const Subsection = require("./Subsection.js")
const Substitute = require("./Substitute.js")
const Subtract = require("./Subtract.js")
const Sum = require("./Sum.js")
const SwapCase = require("./SwapCase.js")
const SwapEndianness = require("./SwapEndianness.js")
const SymmetricDifference = require("./SymmetricDifference.js")
const SyntaxHighlighter = require("./SyntaxHighlighter.js")
const TCPIPChecksum = require("./TCPIPChecksum.js")
const Tail = require("./Tail.js")
const TakeBytes = require("./TakeBytes.js")
const Tar = require("./Tar.js")
const TextEncodingBruteForce = require("./TextEncodingBruteForce.js")
const ToBCD = require("./ToBCD.js")
const ToBase = require("./ToBase.js")
const ToBase32 = require("./ToBase32.js")
const ToBase45 = require("./ToBase45.js")
const ToBase58 = require("./ToBase58.js")
const ToBase62 = require("./ToBase62.js")
const ToBase64 = require("./ToBase64.js")
const ToBase85 = require("./ToBase85.js")
const ToBinary = require("./ToBinary.js")
const ToBraille = require("./ToBraille.js")
const ToCamelCase = require("./ToCamelCase.js")
const ToCaseInsensitiveRegex = require("./ToCaseInsensitiveRegex.js")
const ToCharcode = require("./ToCharcode.js")
const ToDecimal = require("./ToDecimal.js")
const ToHTMLEntity = require("./ToHTMLEntity.js")
const ToHex = require("./ToHex.js")
const ToHexContent = require("./ToHexContent.js")
const ToHexdump = require("./ToHexdump.js")
const ToKebabCase = require("./ToKebabCase.js")
const ToLowerCase = require("./ToLowerCase.js")
const ToMessagePack = require("./ToMessagePack.js")
const ToMorseCode = require("./ToMorseCode.js")
const ToOctal = require("./ToOctal.js")
const ToPunycode = require("./ToPunycode.js")
const ToQuotedPrintable = require("./ToQuotedPrintable.js")
const ToSnakeCase = require("./ToSnakeCase.js")
const ToTable = require("./ToTable.js")
const ToUNIXTimestamp = require("./ToUNIXTimestamp.js")
const ToUpperCase = require("./ToUpperCase.js")
const TranslateDateTimeFormat = require("./TranslateDateTimeFormat.js")
const TripleDESDecrypt = require("./TripleDESDecrypt.js")
const TripleDESEncrypt = require("./TripleDESEncrypt.js")
const Typex = require("./Typex.js")
const UNIXTimestampToWindowsFiletime = require("./UNIXTimestampToWindowsFiletime.js")
const URLDecode = require("./URLDecode.js")
const URLEncode = require("./URLEncode.js")
const UnescapeString = require("./UnescapeString.js")
const UnescapeUnicodeCharacters = require("./UnescapeUnicodeCharacters.js")
const UnicodeTextFormat = require("./UnicodeTextFormat.js")
const Unique = require("./Unique.js")
const Untar = require("./Untar.js")
const Unzip = require("./Unzip.js")
const VarIntDecode = require("./VarIntDecode.js")
const VarIntEncode = require("./VarIntEncode.js")
const ViewBitPlane = require("./ViewBitPlane.js")
const VigenèreDecode = require("./VigenèreDecode.js")
const VigenèreEncode = require("./VigenèreEncode.js")
const Whirlpool = require("./Whirlpool.js")
const WindowsFiletimeToUNIXTimestamp = require("./WindowsFiletimeToUNIXTimestamp.js")
const XKCDRandomNumber = require("./XKCDRandomNumber.js")
const XMLBeautify = require("./XMLBeautify.js")
const XMLMinify = require("./XMLMinify.js")
const XOR = require("./XOR.js")
const XORBruteForce = require("./XORBruteForce.js")
const XPathExpression = require("./XPathExpression.js")
const YARARules = require("./YARARules.js")
const Zip = require("./Zip.js")
const ZlibDeflate = require("./ZlibDeflate.js")
const ZlibInflate = require("./ZlibInflate.js")

module.exports = {
    A1Z26CipherDecode,
    A1Z26CipherEncode,
    ADD,
    AESDecrypt,
    AESEncrypt,
    AESKeyUnwrap,
    AESKeyWrap,
    AMFDecode,
    AMFEncode,
    AND,
    AddLineNumbers,
    AddTextToImage,
    Adler32Checksum,
    AffineCipherDecode,
    AffineCipherEncode,
    AnalyseHash,
    Argon2,
    Argon2Compare,
    AtbashCipher,
    AvroToJSON,
    BLAKE2b,
    BLAKE2s,
    BSONDeserialise,
    BSONSerialise,
    BaconCipherDecode,
    BaconCipherEncode,
    Bcrypt,
    BcryptCompare,
    BcryptParse,
    BifidCipherDecode,
    BifidCipherEncode,
    BitShiftLeft,
    BitShiftRight,
    BlowfishDecrypt,
    BlowfishEncrypt,
    BlurImage,
    Bombe,
    Bzip2Compress,
    Bzip2Decompress,
    CBORDecode,
    CBOREncode,
    CMAC,
    CRC16Checksum,
    CRC32Checksum,
    CRC8Checksum,
    CSSBeautify,
    CSSMinify,
    CSSSelector,
    CSVToJSON,
    CTPH,
    CaesarBoxCipher,
    CartesianProduct,
    CetaceanCipherDecode,
    CetaceanCipherEncode,
    ChaCha,
    ChangeIPFormat,
    ChiSquare,
    CipherSaber2Decrypt,
    CipherSaber2Encrypt,
    CitrixCTX1Decode,
    CitrixCTX1Encode,
    Colossus,
    Comment,
    CompareCTPHHashes,
    CompareSSDEEPHashes,
    ConditionalJump,
    ContainImage,
    ConvertArea,
    ConvertCoordinateFormat,
    ConvertDataUnits,
    ConvertDistance,
    ConvertImageFormat,
    ConvertMass,
    ConvertSpeed,
    ConvertToNATOAlphabet,
    CountOccurrences,
    CoverImage,
    CropImage,
    DESDecrypt,
    DESEncrypt,
    DNSOverHTTPS,
    DechunkHTTPResponse,
    DecodeNetBIOSName,
    DecodeText,
    DefangIPAddresses,
    DefangURL,
    DeriveEVPKey,
    DeriveHKDFKey,
    DerivePBKDF2Key,
    DetectFileType,
    Diff,
    DisassembleX86,
    DitherImage,
    Divide,
    DropBytes,
    ELFInfo,
    EncodeNetBIOSName,
    EncodeText,
    Enigma,
    Entropy,
    EscapeString,
    EscapeUnicodeCharacters,
    ExpandAlphabetRange,
    ExtractDates,
    ExtractDomains,
    ExtractEXIF,
    ExtractEmailAddresses,
    ExtractFilePaths,
    ExtractFiles,
    ExtractID3,
    ExtractIPAddresses,
    ExtractLSB,
    ExtractMACAddresses,
    ExtractRGBA,
    ExtractURLs,
    Filter,
    FindReplace,
    Fletcher16Checksum,
    Fletcher32Checksum,
    Fletcher64Checksum,
    Fletcher8Checksum,
    FlipImage,
    Fork,
    FormatMACAddresses,
    FrequencyDistribution,
    FromBCD,
    FromBase,
    FromBase32,
    FromBase45,
    FromBase58,
    FromBase62,
    FromBase64,
    FromBase85,
    FromBinary,
    FromBraille,
    FromCaseInsensitiveRegex,
    FromCharcode,
    FromDecimal,
    FromHTMLEntity,
    FromHex,
    FromHexContent,
    FromHexdump,
    FromMessagePack,
    FromMorseCode,
    FromOctal,
    FromPunycode,
    FromQuotedPrintable,
    FromUNIXTimestamp,
    FuzzyMatch,
    GOSTHash,
    GenerateAllHashes,
    GenerateDeBruijnSequence,
    GenerateHOTP,
    GenerateImage,
    GenerateLoremIpsum,
    GeneratePGPKeyPair,
    GenerateQRCode,
    GenerateRSAKeyPair,
    GenerateTOTP,
    GenerateUUID,
    GenericCodeBeautify,
    GetAllCasings,
    GetTime,
    GroupIPAddresses,
    Gunzip,
    Gzip,
    HAS160,
    HASSHClientFingerprint,
    HASSHServerFingerprint,
    HMAC,
    HTMLToText,
    HTTPRequest,
    HammingDistance,
    HaversineDistance,
    Head,
    HeatmapChart,
    HexDensityChart,
    HexToObjectIdentifier,
    HexToPEM,
    ImageBrightnessContrast,
    ImageFilter,
    ImageHueSaturationLightness,
    ImageOpacity,
    IndexOfCoincidence,
    InvertImage,
    JA3Fingerprint,
    JA3SFingerprint,
    JPathExpression,
    JSONBeautify,
    JSONMinify,
    JSONToCSV,
    JWTDecode,
    JWTSign,
    JWTVerify,
    JavaScriptBeautify,
    JavaScriptMinify,
    JavaScriptParser,
    Jump,
    Keccak,
    LMHash,
    LS47Decrypt,
    LS47Encrypt,
    LZ4Compress,
    LZ4Decompress,
    LZMACompress,
    LZMADecompress,
    LZStringCompress,
    LZStringDecompress,
    Label,
    LevenshteinDistance,
    Lorenz,
    LuhnChecksum,
    MD2,
    MD4,
    MD5,
    MD6,
    Magic,
    Mean,
    Median,
    Merge,
    MicrosoftScriptDecoder,
    MultipleBombe,
    Multiply,
    NOT,
    NTHash,
    NormaliseImage,
    NormaliseUnicode,
    Numberwang,
    OR,
    ObjectIdentifierToHex,
    OffsetChecker,
    OpticalCharacterRecognition,
    PEMToHex,
    PGPDecrypt,
    PGPDecryptAndVerify,
    PGPEncrypt,
    PGPEncryptAndSign,
    PGPVerify,
    PHPDeserialize,
    PLISTViewer,
    PadLines,
    ParseASN1HexString,
    ParseColourCode,
    ParseDateTime,
    ParseIPRange,
    ParseIPv4Header,
    ParseIPv6Address,
    ParseObjectIDTimestamp,
    ParseQRCode,
    ParseSSHHostKey,
    ParseTCP,
    ParseTLV,
    ParseUDP,
    ParseUNIXFilePermissions,
    ParseURI,
    ParseUserAgent,
    ParseX509Certificate,
    PlayMedia,
    PowerSet,
    ProtobufDecode,
    ProtobufEncode,
    PseudoRandomNumberGenerator,
    RC2Decrypt,
    RC2Encrypt,
    RC4,
    RC4Drop,
    RIPEMD,
    ROT13,
    ROT13BruteForce,
    ROT47,
    ROT47BruteForce,
    ROT8000,
    RSADecrypt,
    RSAEncrypt,
    RSASign,
    RSAVerify,
    Rabbit,
    RailFenceCipherDecode,
    RailFenceCipherEncode,
    RandomizeColourPalette,
    RawDeflate,
    RawInflate,
    Register,
    RegularExpression,
    RemoveDiacritics,
    RemoveEXIF,
    RemoveLineNumbers,
    RemoveNullBytes,
    RemoveWhitespace,
    RenderImage,
    RenderMarkdown,
    ResizeImage,
    Return,
    Reverse,
    RotateImage,
    RotateLeft,
    RotateRight,
    SHA0,
    SHA1,
    SHA2,
    SHA3,
    SIGABA,
    SM3,
    SM4Decrypt,
    SM4Encrypt,
    SQLBeautify,
    SQLMinify,
    SSDEEP,
    SUB,
    ScanForEmbeddedFiles,
    ScatterChart,
    Scrypt,
    SeriesChart,
    SetDifference,
    SetIntersection,
    SetUnion,
    Shake,
    SharpenImage,
    ShowBase64Offsets,
    ShowOnMap,
    Shuffle,
    Sleep,
    Snefru,
    Sort,
    Split,
    SplitColourChannels,
    StandardDeviation,
    Streebog,
    Strings,
    StripHTMLTags,
    StripHTTPHeaders,
    Subsection,
    Substitute,
    Subtract,
    Sum,
    SwapCase,
    SwapEndianness,
    SymmetricDifference,
    SyntaxHighlighter,
    TCPIPChecksum,
    Tail,
    TakeBytes,
    Tar,
    TextEncodingBruteForce,
    ToBCD,
    ToBase,
    ToBase32,
    ToBase45,
    ToBase58,
    ToBase62,
    ToBase64,
    ToBase85,
    ToBinary,
    ToBraille,
    ToCamelCase,
    ToCaseInsensitiveRegex,
    ToCharcode,
    ToDecimal,
    ToHTMLEntity,
    ToHex,
    ToHexContent,
    ToHexdump,
    ToKebabCase,
    ToLowerCase,
    ToMessagePack,
    ToMorseCode,
    ToOctal,
    ToPunycode,
    ToQuotedPrintable,
    ToSnakeCase,
    ToTable,
    ToUNIXTimestamp,
    ToUpperCase,
    TranslateDateTimeFormat,
    TripleDESDecrypt,
    TripleDESEncrypt,
    Typex,
    UNIXTimestampToWindowsFiletime,
    URLDecode,
    URLEncode,
    UnescapeString,
    UnescapeUnicodeCharacters,
    UnicodeTextFormat,
    Unique,
    Untar,
    Unzip,
    VarIntDecode,
    VarIntEncode,
    ViewBitPlane,
    VigenèreDecode,
    VigenèreEncode,
    Whirlpool,
    WindowsFiletimeToUNIXTimestamp,
    XKCDRandomNumber,
    XMLBeautify,
    XMLMinify,
    XOR,
    XORBruteForce,
    XPathExpression,
    YARARules,
    Zip,
    ZlibDeflate,
    ZlibInflate,
};
