/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
const A1Z26CipherDecode = require("../../operations/A1Z26CipherDecode.js")
const A1Z26CipherEncode = require("../../operations/A1Z26CipherEncode.js")
const AESDecrypt = require("../../operations/AESDecrypt.js")
const AESEncrypt = require("../../operations/AESEncrypt.js")
const AESKeyUnwrap = require("../../operations/AESKeyUnwrap.js")
const AESKeyWrap = require("../../operations/AESKeyWrap.js")
const AffineCipherDecode = require("../../operations/AffineCipherDecode.js")
const AffineCipherEncode = require("../../operations/AffineCipherEncode.js")
const AtbashCipher = require("../../operations/AtbashCipher.js")
const BifidCipherDecode = require("../../operations/BifidCipherDecode.js")
const BifidCipherEncode = require("../../operations/BifidCipherEncode.js")
const BlowfishDecrypt = require("../../operations/BlowfishDecrypt.js")
const BlowfishEncrypt = require("../../operations/BlowfishEncrypt.js")
const CaesarBoxCipher = require("../../operations/CaesarBoxCipher.js")
const CetaceanCipherDecode = require("../../operations/CetaceanCipherDecode.js")
const CetaceanCipherEncode = require("../../operations/CetaceanCipherEncode.js")
const DESDecrypt = require("../../operations/DESDecrypt.js")
const DESEncrypt = require("../../operations/DESEncrypt.js")
const DeriveEVPKey = require("../../operations/DeriveEVPKey.js")
const DerivePBKDF2Key = require("../../operations/DerivePBKDF2Key.js")
const GenerateRSAKeyPair = require("../../operations/GenerateRSAKeyPair.js")
const PseudoRandomNumberGenerator = require("../../operations/PseudoRandomNumberGenerator.js")
const RC2Decrypt = require("../../operations/RC2Decrypt.js")
const RC2Encrypt = require("../../operations/RC2Encrypt.js")
const RC4 = require("../../operations/RC4.js")
const RC4Drop = require("../../operations/RC4Drop.js")
const RSADecrypt = require("../../operations/RSADecrypt.js")
const RSAEncrypt = require("../../operations/RSAEncrypt.js")
const RSASign = require("../../operations/RSASign.js")
const RSAVerify = require("../../operations/RSAVerify.js")
const Rabbit = require("../../operations/Rabbit.js")
const RailFenceCipherDecode = require("../../operations/RailFenceCipherDecode.js")
const RailFenceCipherEncode = require("../../operations/RailFenceCipherEncode.js")
const SM4Decrypt = require("../../operations/SM4Decrypt.js")
const SM4Encrypt = require("../../operations/SM4Encrypt.js")
const TripleDESDecrypt = require("../../operations/TripleDESDecrypt.js")
const TripleDESEncrypt = require("../../operations/TripleDESEncrypt.js")
const VigenèreDecode = require("../../operations/VigenèreDecode.js")
const VigenèreEncode = require("../../operations/VigenèreEncode.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Ciphers = {
    "A1Z26 Cipher Decode": A1Z26CipherDecode,
    "A1Z26 Cipher Encode": A1Z26CipherEncode,
    "AES Decrypt": AESDecrypt,
    "AES Encrypt": AESEncrypt,
    "AES Key Unwrap": AESKeyUnwrap,
    "AES Key Wrap": AESKeyWrap,
    "Affine Cipher Decode": AffineCipherDecode,
    "Affine Cipher Encode": AffineCipherEncode,
    "Atbash Cipher": AtbashCipher,
    "Bifid Cipher Decode": BifidCipherDecode,
    "Bifid Cipher Encode": BifidCipherEncode,
    "Blowfish Decrypt": BlowfishDecrypt,
    "Blowfish Encrypt": BlowfishEncrypt,
    "Caesar Box Cipher": CaesarBoxCipher,
    "Cetacean Cipher Decode": CetaceanCipherDecode,
    "Cetacean Cipher Encode": CetaceanCipherEncode,
    "DES Decrypt": DESDecrypt,
    "DES Encrypt": DESEncrypt,
    "Derive EVP key": DeriveEVPKey,
    "Derive PBKDF2 key": DerivePBKDF2Key,
    "Generate RSA Key Pair": GenerateRSAKeyPair,
    "Pseudo-Random Number Generator": PseudoRandomNumberGenerator,
    "RC2 Decrypt": RC2Decrypt,
    "RC2 Encrypt": RC2Encrypt,
    "RC4": RC4,
    "RC4 Drop": RC4Drop,
    "RSA Decrypt": RSADecrypt,
    "RSA Encrypt": RSAEncrypt,
    "RSA Sign": RSASign,
    "RSA Verify": RSAVerify,
    "Rabbit": Rabbit,
    "Rail Fence Cipher Decode": RailFenceCipherDecode,
    "Rail Fence Cipher Encode": RailFenceCipherEncode,
    "SM4 Decrypt": SM4Decrypt,
    "SM4 Encrypt": SM4Encrypt,
    "Triple DES Decrypt": TripleDESDecrypt,
    "Triple DES Encrypt": TripleDESEncrypt,
    "Vigenère Decode": VigenèreDecode,
    "Vigenère Encode": VigenèreEncode,
};

module.exports = OpModules;
