/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
const CSSBeautify = require("../../operations/CSSBeautify.js")
const CSSMinify = require("../../operations/CSSMinify.js")
const CSSSelector = require("../../operations/CSSSelector.js")
const FromMessagePack = require("../../operations/FromMessagePack.js")
const GenericCodeBeautify = require("../../operations/GenericCodeBeautify.js")
const JPathExpression = require("../../operations/JPathExpression.js")
const JSONBeautify = require("../../operations/JSONBeautify.js")
const JSONMinify = require("../../operations/JSONMinify.js")
const JavaScriptBeautify = require("../../operations/JavaScriptBeautify.js")
const JavaScriptMinify = require("../../operations/JavaScriptMinify.js")
const JavaScriptParser = require("../../operations/JavaScriptParser.js")
const RenderMarkdown = require("../../operations/RenderMarkdown.js")
const SQLBeautify = require("../../operations/SQLBeautify.js")
const SQLMinify = require("../../operations/SQLMinify.js")
const SyntaxHighlighter = require("../../operations/SyntaxHighlighter.js")
const ToCamelCase = require("../../operations/ToCamelCase.js")
const ToKebabCase = require("../../operations/ToKebabCase.js")
const ToMessagePack = require("../../operations/ToMessagePack.js")
const ToSnakeCase = require("../../operations/ToSnakeCase.js")
const XMLBeautify = require("../../operations/XMLBeautify.js")
const XMLMinify = require("../../operations/XMLMinify.js")
const XPathExpression = require("../../operations/XPathExpression.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Code = {
    "CSS Beautify": CSSBeautify,
    "CSS Minify": CSSMinify,
    "CSS selector": CSSSelector,
    "From MessagePack": FromMessagePack,
    "Generic Code Beautify": GenericCodeBeautify,
    "JPath expression": JPathExpression,
    "JSON Beautify": JSONBeautify,
    "JSON Minify": JSONMinify,
    "JavaScript Beautify": JavaScriptBeautify,
    "JavaScript Minify": JavaScriptMinify,
    "JavaScript Parser": JavaScriptParser,
    "Render Markdown": RenderMarkdown,
    "SQL Beautify": SQLBeautify,
    "SQL Minify": SQLMinify,
    "Syntax highlighter": SyntaxHighlighter,
    "To Camel case": ToCamelCase,
    "To Kebab case": ToKebabCase,
    "To MessagePack": ToMessagePack,
    "To Snake case": ToSnakeCase,
    "XML Beautify": XMLBeautify,
    "XML Minify": XMLMinify,
    "XPath expression": XPathExpression,
};

module.exports = OpModules;
