/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
const Bzip2Compress = require("../../operations/Bzip2Compress.js")
const Bzip2Decompress = require("../../operations/Bzip2Decompress.js")
const Gunzip = require("../../operations/Gunzip.js")
const Gzip = require("../../operations/Gzip.js")
const LZ4Compress = require("../../operations/LZ4Compress.js")
const LZ4Decompress = require("../../operations/LZ4Decompress.js")
const LZMACompress = require("../../operations/LZMACompress.js")
const LZMADecompress = require("../../operations/LZMADecompress.js")
const LZStringCompress = require("../../operations/LZStringCompress.js")
const LZStringDecompress = require("../../operations/LZStringDecompress.js")
const RawDeflate = require("../../operations/RawDeflate.js")
const RawInflate = require("../../operations/RawInflate.js")
const Tar = require("../../operations/Tar.js")
const Untar = require("../../operations/Untar.js")
const Unzip = require("../../operations/Unzip.js")
const Zip = require("../../operations/Zip.js")
const ZlibDeflate = require("../../operations/ZlibDeflate.js")
const ZlibInflate = require("../../operations/ZlibInflate.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Compression = {
    "Bzip2 Compress": Bzip2Compress,
    "Bzip2 Decompress": Bzip2Decompress,
    "Gunzip": Gunzip,
    "Gzip": Gzip,
    "LZ4 Compress": LZ4Compress,
    "LZ4 Decompress": LZ4Decompress,
    "LZMA Compress": LZMACompress,
    "LZMA Decompress": LZMADecompress,
    "LZString Compress": LZStringCompress,
    "LZString Decompress": LZStringDecompress,
    "Raw Deflate": RawDeflate,
    "Raw Inflate": RawInflate,
    "Tar": Tar,
    "Untar": Untar,
    "Unzip": Unzip,
    "Zip": Zip,
    "Zlib Deflate": ZlibDeflate,
    "Zlib Inflate": ZlibInflate,
};

module.exports = OpModules;
