/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
const ADD = require("../../operations/ADD.js")
const AND = require("../../operations/AND.js")
const AddLineNumbers = require("../../operations/AddLineNumbers.js")
const BaconCipherDecode = require("../../operations/BaconCipherDecode.js")
const BaconCipherEncode = require("../../operations/BaconCipherEncode.js")
const BitShiftLeft = require("../../operations/BitShiftLeft.js")
const BitShiftRight = require("../../operations/BitShiftRight.js")
const CSVToJSON = require("../../operations/CSVToJSON.js")
const CartesianProduct = require("../../operations/CartesianProduct.js")
const ChaCha = require("../../operations/ChaCha.js")
const ChangeIPFormat = require("../../operations/ChangeIPFormat.js")
const ChiSquare = require("../../operations/ChiSquare.js")
const Comment = require("../../operations/Comment.js")
const ConditionalJump = require("../../operations/ConditionalJump.js")
const ConvertArea = require("../../operations/ConvertArea.js")
const ConvertDataUnits = require("../../operations/ConvertDataUnits.js")
const ConvertDistance = require("../../operations/ConvertDistance.js")
const ConvertMass = require("../../operations/ConvertMass.js")
const ConvertSpeed = require("../../operations/ConvertSpeed.js")
const ConvertToNATOAlphabet = require("../../operations/ConvertToNATOAlphabet.js")
const CountOccurrences = require("../../operations/CountOccurrences.js")
const DNSOverHTTPS = require("../../operations/DNSOverHTTPS.js")
const DechunkHTTPResponse = require("../../operations/DechunkHTTPResponse.js")
const DecodeNetBIOSName = require("../../operations/DecodeNetBIOSName.js")
const DefangIPAddresses = require("../../operations/DefangIPAddresses.js")
const DefangURL = require("../../operations/DefangURL.js")
const DetectFileType = require("../../operations/DetectFileType.js")
const Divide = require("../../operations/Divide.js")
const DropBytes = require("../../operations/DropBytes.js")
const ELFInfo = require("../../operations/ELFInfo.js")
const EncodeNetBIOSName = require("../../operations/EncodeNetBIOSName.js")
const EscapeString = require("../../operations/EscapeString.js")
const EscapeUnicodeCharacters = require("../../operations/EscapeUnicodeCharacters.js")
const ExpandAlphabetRange = require("../../operations/ExpandAlphabetRange.js")
const ExtractFiles = require("../../operations/ExtractFiles.js")
const ExtractID3 = require("../../operations/ExtractID3.js")
const Fork = require("../../operations/Fork.js")
const FormatMACAddresses = require("../../operations/FormatMACAddresses.js")
const FrequencyDistribution = require("../../operations/FrequencyDistribution.js")
const FromBCD = require("../../operations/FromBCD.js")
const FromBase = require("../../operations/FromBase.js")
const FromBase32 = require("../../operations/FromBase32.js")
const FromBase45 = require("../../operations/FromBase45.js")
const FromBase58 = require("../../operations/FromBase58.js")
const FromBase62 = require("../../operations/FromBase62.js")
const FromBase64 = require("../../operations/FromBase64.js")
const FromBase85 = require("../../operations/FromBase85.js")
const FromBinary = require("../../operations/FromBinary.js")
const FromBraille = require("../../operations/FromBraille.js")
const FromCaseInsensitiveRegex = require("../../operations/FromCaseInsensitiveRegex.js")
const FromCharcode = require("../../operations/FromCharcode.js")
const FromDecimal = require("../../operations/FromDecimal.js")
const FromHex = require("../../operations/FromHex.js")
const FromHexContent = require("../../operations/FromHexContent.js")
const FromHexdump = require("../../operations/FromHexdump.js")
const FromMorseCode = require("../../operations/FromMorseCode.js")
const FromOctal = require("../../operations/FromOctal.js")
const FromQuotedPrintable = require("../../operations/FromQuotedPrintable.js")
const FromUNIXTimestamp = require("../../operations/FromUNIXTimestamp.js")
const FuzzyMatch = require("../../operations/FuzzyMatch.js")
const GenerateDeBruijnSequence = require("../../operations/GenerateDeBruijnSequence.js")
const GenerateHOTP = require("../../operations/GenerateHOTP.js")
const GenerateLoremIpsum = require("../../operations/GenerateLoremIpsum.js")
const GenerateTOTP = require("../../operations/GenerateTOTP.js")
const GetAllCasings = require("../../operations/GetAllCasings.js")
const GetTime = require("../../operations/GetTime.js")
const GroupIPAddresses = require("../../operations/GroupIPAddresses.js")
const HTMLToText = require("../../operations/HTMLToText.js")
const HTTPRequest = require("../../operations/HTTPRequest.js")
const HammingDistance = require("../../operations/HammingDistance.js")
const HaversineDistance = require("../../operations/HaversineDistance.js")
const Head = require("../../operations/Head.js")
const IndexOfCoincidence = require("../../operations/IndexOfCoincidence.js")
const JSONToCSV = require("../../operations/JSONToCSV.js")
const Jump = require("../../operations/Jump.js")
const Label = require("../../operations/Label.js")
const LevenshteinDistance = require("../../operations/LevenshteinDistance.js")
const LuhnChecksum = require("../../operations/LuhnChecksum.js")
const Magic = require("../../operations/Magic.js")
const Mean = require("../../operations/Mean.js")
const Median = require("../../operations/Median.js")
const Merge = require("../../operations/Merge.js")
const MicrosoftScriptDecoder = require("../../operations/MicrosoftScriptDecoder.js")
const Multiply = require("../../operations/Multiply.js")
const NOT = require("../../operations/NOT.js")
const Numberwang = require("../../operations/Numberwang.js")
const OR = require("../../operations/OR.js")
const OffsetChecker = require("../../operations/OffsetChecker.js")
const PEMToHex = require("../../operations/PEMToHex.js")
const PHPDeserialize = require("../../operations/PHPDeserialize.js")
const PLISTViewer = require("../../operations/PLISTViewer.js")
const PadLines = require("../../operations/PadLines.js")
const ParseColourCode = require("../../operations/ParseColourCode.js")
const ParseDateTime = require("../../operations/ParseDateTime.js")
const ParseIPRange = require("../../operations/ParseIPRange.js")
const ParseIPv4Header = require("../../operations/ParseIPv4Header.js")
const ParseIPv6Address = require("../../operations/ParseIPv6Address.js")
const ParseSSHHostKey = require("../../operations/ParseSSHHostKey.js")
const ParseTCP = require("../../operations/ParseTCP.js")
const ParseTLV = require("../../operations/ParseTLV.js")
const ParseUDP = require("../../operations/ParseUDP.js")
const ParseUNIXFilePermissions = require("../../operations/ParseUNIXFilePermissions.js")
const PlayMedia = require("../../operations/PlayMedia.js")
const PowerSet = require("../../operations/PowerSet.js")
const ROT13 = require("../../operations/ROT13.js")
const ROT13BruteForce = require("../../operations/ROT13BruteForce.js")
const ROT47 = require("../../operations/ROT47.js")
const ROT47BruteForce = require("../../operations/ROT47BruteForce.js")
const ROT8000 = require("../../operations/ROT8000.js")
const RemoveDiacritics = require("../../operations/RemoveDiacritics.js")
const RemoveLineNumbers = require("../../operations/RemoveLineNumbers.js")
const RemoveNullBytes = require("../../operations/RemoveNullBytes.js")
const RemoveWhitespace = require("../../operations/RemoveWhitespace.js")
const Return = require("../../operations/Return.js")
const Reverse = require("../../operations/Reverse.js")
const RotateLeft = require("../../operations/RotateLeft.js")
const RotateRight = require("../../operations/RotateRight.js")
const SUB = require("../../operations/SUB.js")
const ScanForEmbeddedFiles = require("../../operations/ScanForEmbeddedFiles.js")
const SetDifference = require("../../operations/SetDifference.js")
const SetIntersection = require("../../operations/SetIntersection.js")
const SetUnion = require("../../operations/SetUnion.js")
const ShowBase64Offsets = require("../../operations/ShowBase64Offsets.js")
const Shuffle = require("../../operations/Shuffle.js")
const Sleep = require("../../operations/Sleep.js")
const Sort = require("../../operations/Sort.js")
const Split = require("../../operations/Split.js")
const StandardDeviation = require("../../operations/StandardDeviation.js")
const StripHTMLTags = require("../../operations/StripHTMLTags.js")
const StripHTTPHeaders = require("../../operations/StripHTTPHeaders.js")
const Subsection = require("../../operations/Subsection.js")
const Substitute = require("../../operations/Substitute.js")
const Subtract = require("../../operations/Subtract.js")
const Sum = require("../../operations/Sum.js")
const SwapCase = require("../../operations/SwapCase.js")
const SwapEndianness = require("../../operations/SwapEndianness.js")
const SymmetricDifference = require("../../operations/SymmetricDifference.js")
const Tail = require("../../operations/Tail.js")
const TakeBytes = require("../../operations/TakeBytes.js")
const ToBCD = require("../../operations/ToBCD.js")
const ToBase = require("../../operations/ToBase.js")
const ToBase32 = require("../../operations/ToBase32.js")
const ToBase45 = require("../../operations/ToBase45.js")
const ToBase58 = require("../../operations/ToBase58.js")
const ToBase62 = require("../../operations/ToBase62.js")
const ToBase64 = require("../../operations/ToBase64.js")
const ToBase85 = require("../../operations/ToBase85.js")
const ToBinary = require("../../operations/ToBinary.js")
const ToBraille = require("../../operations/ToBraille.js")
const ToCaseInsensitiveRegex = require("../../operations/ToCaseInsensitiveRegex.js")
const ToCharcode = require("../../operations/ToCharcode.js")
const ToDecimal = require("../../operations/ToDecimal.js")
const ToHex = require("../../operations/ToHex.js")
const ToHexContent = require("../../operations/ToHexContent.js")
const ToHexdump = require("../../operations/ToHexdump.js")
const ToLowerCase = require("../../operations/ToLowerCase.js")
const ToMorseCode = require("../../operations/ToMorseCode.js")
const ToOctal = require("../../operations/ToOctal.js")
const ToQuotedPrintable = require("../../operations/ToQuotedPrintable.js")
const ToTable = require("../../operations/ToTable.js")
const ToUNIXTimestamp = require("../../operations/ToUNIXTimestamp.js")
const ToUpperCase = require("../../operations/ToUpperCase.js")
const TranslateDateTimeFormat = require("../../operations/TranslateDateTimeFormat.js")
const UNIXTimestampToWindowsFiletime = require("../../operations/UNIXTimestampToWindowsFiletime.js")
const UnescapeString = require("../../operations/UnescapeString.js")
const UnescapeUnicodeCharacters = require("../../operations/UnescapeUnicodeCharacters.js")
const UnicodeTextFormat = require("../../operations/UnicodeTextFormat.js")
const Unique = require("../../operations/Unique.js")
const VarIntDecode = require("../../operations/VarIntDecode.js")
const VarIntEncode = require("../../operations/VarIntEncode.js")
const WindowsFiletimeToUNIXTimestamp = require("../../operations/WindowsFiletimeToUNIXTimestamp.js")
const XKCDRandomNumber = require("../../operations/XKCDRandomNumber.js")
const XOR = require("../../operations/XOR.js")
const XORBruteForce = require("../../operations/XORBruteForce.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Default = {
    "ADD": ADD,
    "AND": AND,
    "Add line numbers": AddLineNumbers,
    "Bacon Cipher Decode": BaconCipherDecode,
    "Bacon Cipher Encode": BaconCipherEncode,
    "Bit shift left": BitShiftLeft,
    "Bit shift right": BitShiftRight,
    "CSV to JSON": CSVToJSON,
    "Cartesian Product": CartesianProduct,
    "ChaCha": ChaCha,
    "Change IP format": ChangeIPFormat,
    "Chi Square": ChiSquare,
    "Comment": Comment,
    "Conditional Jump": ConditionalJump,
    "Convert area": ConvertArea,
    "Convert data units": ConvertDataUnits,
    "Convert distance": ConvertDistance,
    "Convert mass": ConvertMass,
    "Convert speed": ConvertSpeed,
    "Convert to NATO alphabet": ConvertToNATOAlphabet,
    "Count occurrences": CountOccurrences,
    "DNS over HTTPS": DNSOverHTTPS,
    "Dechunk HTTP response": DechunkHTTPResponse,
    "Decode NetBIOS Name": DecodeNetBIOSName,
    "Defang IP Addresses": DefangIPAddresses,
    "Defang URL": DefangURL,
    "Detect File Type": DetectFileType,
    "Divide": Divide,
    "Drop bytes": DropBytes,
    "ELF Info": ELFInfo,
    "Encode NetBIOS Name": EncodeNetBIOSName,
    "Escape string": EscapeString,
    "Escape Unicode Characters": EscapeUnicodeCharacters,
    "Expand alphabet range": ExpandAlphabetRange,
    "Extract Files": ExtractFiles,
    "Extract ID3": ExtractID3,
    "Fork": Fork,
    "Format MAC addresses": FormatMACAddresses,
    "Frequency distribution": FrequencyDistribution,
    "From BCD": FromBCD,
    "From Base": FromBase,
    "From Base32": FromBase32,
    "From Base45": FromBase45,
    "From Base58": FromBase58,
    "From Base62": FromBase62,
    "From Base64": FromBase64,
    "From Base85": FromBase85,
    "From Binary": FromBinary,
    "From Braille": FromBraille,
    "From Case Insensitive Regex": FromCaseInsensitiveRegex,
    "From Charcode": FromCharcode,
    "From Decimal": FromDecimal,
    "From Hex": FromHex,
    "From Hex Content": FromHexContent,
    "From Hexdump": FromHexdump,
    "From Morse Code": FromMorseCode,
    "From Octal": FromOctal,
    "From Quoted Printable": FromQuotedPrintable,
    "From UNIX Timestamp": FromUNIXTimestamp,
    "Fuzzy Match": FuzzyMatch,
    "Generate De Bruijn Sequence": GenerateDeBruijnSequence,
    "Generate HOTP": GenerateHOTP,
    "Generate Lorem Ipsum": GenerateLoremIpsum,
    "Generate TOTP": GenerateTOTP,
    "Get All Casings": GetAllCasings,
    "Get Time": GetTime,
    "Group IP addresses": GroupIPAddresses,
    "HTML To Text": HTMLToText,
    "HTTP request": HTTPRequest,
    "Hamming Distance": HammingDistance,
    "Haversine distance": HaversineDistance,
    "Head": Head,
    "Index of Coincidence": IndexOfCoincidence,
    "JSON to CSV": JSONToCSV,
    "Jump": Jump,
    "Label": Label,
    "Levenshtein Distance": LevenshteinDistance,
    "Luhn Checksum": LuhnChecksum,
    "Magic": Magic,
    "Mean": Mean,
    "Median": Median,
    "Merge": Merge,
    "Microsoft Script Decoder": MicrosoftScriptDecoder,
    "Multiply": Multiply,
    "NOT": NOT,
    "Numberwang": Numberwang,
    "OR": OR,
    "Offset checker": OffsetChecker,
    "PEM to Hex": PEMToHex,
    "PHP Deserialize": PHPDeserialize,
    "P-list Viewer": PLISTViewer,
    "Pad lines": PadLines,
    "Parse colour code": ParseColourCode,
    "Parse DateTime": ParseDateTime,
    "Parse IP range": ParseIPRange,
    "Parse IPv4 header": ParseIPv4Header,
    "Parse IPv6 address": ParseIPv6Address,
    "Parse SSH Host Key": ParseSSHHostKey,
    "Parse TCP": ParseTCP,
    "Parse TLV": ParseTLV,
    "Parse UDP": ParseUDP,
    "Parse UNIX file permissions": ParseUNIXFilePermissions,
    "Play Media": PlayMedia,
    "Power Set": PowerSet,
    "ROT13": ROT13,
    "ROT13 Brute Force": ROT13BruteForce,
    "ROT47": ROT47,
    "ROT47 Brute Force": ROT47BruteForce,
    "ROT8000": ROT8000,
    "Remove Diacritics": RemoveDiacritics,
    "Remove line numbers": RemoveLineNumbers,
    "Remove null bytes": RemoveNullBytes,
    "Remove whitespace": RemoveWhitespace,
    "Return": Return,
    "Reverse": Reverse,
    "Rotate left": RotateLeft,
    "Rotate right": RotateRight,
    "SUB": SUB,
    "Scan for Embedded Files": ScanForEmbeddedFiles,
    "Set Difference": SetDifference,
    "Set Intersection": SetIntersection,
    "Set Union": SetUnion,
    "Show Base64 offsets": ShowBase64Offsets,
    "Shuffle": Shuffle,
    "Sleep": Sleep,
    "Sort": Sort,
    "Split": Split,
    "Standard Deviation": StandardDeviation,
    "Strip HTML tags": StripHTMLTags,
    "Strip HTTP headers": StripHTTPHeaders,
    "Subsection": Subsection,
    "Substitute": Substitute,
    "Subtract": Subtract,
    "Sum": Sum,
    "Swap case": SwapCase,
    "Swap endianness": SwapEndianness,
    "Symmetric Difference": SymmetricDifference,
    "Tail": Tail,
    "Take bytes": TakeBytes,
    "To BCD": ToBCD,
    "To Base": ToBase,
    "To Base32": ToBase32,
    "To Base45": ToBase45,
    "To Base58": ToBase58,
    "To Base62": ToBase62,
    "To Base64": ToBase64,
    "To Base85": ToBase85,
    "To Binary": ToBinary,
    "To Braille": ToBraille,
    "To Case Insensitive Regex": ToCaseInsensitiveRegex,
    "To Charcode": ToCharcode,
    "To Decimal": ToDecimal,
    "To Hex": ToHex,
    "To Hex Content": ToHexContent,
    "To Hexdump": ToHexdump,
    "To Lower case": ToLowerCase,
    "To Morse Code": ToMorseCode,
    "To Octal": ToOctal,
    "To Quoted Printable": ToQuotedPrintable,
    "To Table": ToTable,
    "To UNIX Timestamp": ToUNIXTimestamp,
    "To Upper case": ToUpperCase,
    "Translate DateTime Format": TranslateDateTimeFormat,
    "UNIX Timestamp to Windows Filetime": UNIXTimestampToWindowsFiletime,
    "Unescape string": UnescapeString,
    "Unescape Unicode Characters": UnescapeUnicodeCharacters,
    "Unicode Text Format": UnicodeTextFormat,
    "Unique": Unique,
    "VarInt Decode": VarIntDecode,
    "VarInt Encode": VarIntEncode,
    "Windows Filetime to UNIX Timestamp": WindowsFiletimeToUNIXTimestamp,
    "XKCD Random Number": XKCDRandomNumber,
    "XOR": XOR,
    "XOR Brute Force": XORBruteForce,
};

module.exports = OpModules;
