/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
const Diff = require("../../operations/Diff.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Diff = {
    "Diff": Diff,
};

module.exports = OpModules;
