/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
const BLAKE2b = require("../../operations/BLAKE2b.js")
const BLAKE2s = require("../../operations/BLAKE2s.js")
const ConvertCoordinateFormat = require("../../operations/ConvertCoordinateFormat.js")
const GOSTHash = require("../../operations/GOSTHash.js")
const ShowOnMap = require("../../operations/ShowOnMap.js")
const Streebog = require("../../operations/Streebog.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Hashing = {
    "BLAKE2b": BLAKE2b,
    "BLAKE2s": BLAKE2s,
    "Convert co-ordinate format": ConvertCoordinateFormat,
    "GOST hash": GOSTHash,
    "Show on map": ShowOnMap,
    "Streebog": Streebog,
};

module.exports = OpModules;
