/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* Imports all modules for builds which do not load modules separately.
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
const CiphersModule = require("./Ciphers.js")
const DefaultModule = require("./Default.js")
const EncodingsModule = require("./Encodings.js")
const ImageModule = require("./Image.js")
const CryptoModule = require("./Crypto.js")
const SerialiseModule = require("./Serialise.js")
const HashingModule = require("./Hashing.js")
const BletchleyModule = require("./Bletchley.js")
const CompressionModule = require("./Compression.js")
const CodeModule = require("./Code.js")
const DiffModule = require("./Diff.js")
const ShellcodeModule = require("./Shellcode.js")
const ChartsModule = require("./Charts.js")
const RegexModule = require("./Regex.js")
const PGPModule = require("./PGP.js")
const PublicKeyModule = require("./PublicKey.js")
const OCRModule = require("./OCR.js")
const URLModule = require("./URL.js")
const UserAgentModule = require("./UserAgent.js")
const ProtobufModule = require("./Protobuf.js")
const YaraModule = require("./Yara.js")

const OpModules = {};

Object.assign(
    OpModules,
    CiphersModule,
    DefaultModule,
    EncodingsModule,
    ImageModule,
    CryptoModule,
    SerialiseModule,
    HashingModule,
    BletchleyModule,
    CompressionModule,
    CodeModule,
    DiffModule,
    ShellcodeModule,
    ChartsModule,
    RegexModule,
    PGPModule,
    PublicKeyModule,
    OCRModule,
    URLModule,
    UserAgentModule,
    ProtobufModule,
    YaraModule,
);

module.exports = OpModules;
