/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
const HexToObjectIdentifier = require("../../operations/HexToObjectIdentifier.js")
const HexToPEM = require("../../operations/HexToPEM.js")
const ObjectIdentifierToHex = require("../../operations/ObjectIdentifierToHex.js")
const ParseASN1HexString = require("../../operations/ParseASN1HexString.js")
const ParseX509Certificate = require("../../operations/ParseX509Certificate.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PublicKey = {
    "Hex to Object Identifier": HexToObjectIdentifier,
    "Hex to PEM": HexToPEM,
    "Object Identifier to Hex": ObjectIdentifierToHex,
    "Parse ASN.1 hex string": ParseASN1HexString,
    "Parse X.509 certificate": ParseX509Certificate,
};

module.exports = OpModules;
