/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
const AvroToJSON = require("../../operations/AvroToJSON.js")
const BSONDeserialise = require("../../operations/BSONDeserialise.js")
const BSONSerialise = require("../../operations/BSONSerialise.js")
const CBORDecode = require("../../operations/CBORDecode.js")
const CBOREncode = require("../../operations/CBOREncode.js")
const ParseObjectIDTimestamp = require("../../operations/ParseObjectIDTimestamp.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Serialise = {
    "Avro to JSON": AvroToJSON,
    "BSON deserialise": BSONDeserialise,
    "BSON serialise": BSONSerialise,
    "CBOR Decode": CBORDecode,
    "CBOR Encode": CBOREncode,
    "Parse ObjectID timestamp": ParseObjectIDTimestamp,
};

module.exports = OpModules;
