/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
const DisassembleX86 = require("../../operations/DisassembleX86.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Shellcode = {
    "Disassemble x86": DisassembleX86,
};

module.exports = OpModules;
