/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
const ParseURI = require("../../operations/ParseURI.js")
const URLDecode = require("../../operations/URLDecode.js")
const URLEncode = require("../../operations/URLEncode.js")

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.URL = {
    "Parse URI": ParseURI,
    "URL Decode": URLDecode,
    "URL Encode": URLEncode,
};

module.exports = OpModules;
